server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: fleet-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/locomotives/**

            - id: telemetry-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/telemetry/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
